### PR TITLE
Logging added to Symphony

### PR DESCRIPTION
**Pull request by hrishileanplum**
What              | Where/Who
------------------|----------------------------------------
JIRA Issue        | [JIRA_TICKET_ID](https://leanplum.atlassian.net/browse/JIRA_TICKET_ID)
People Involved   | @colleague1, @colleague2

[Notes on PR descriptions](https://leanplum.atlassian.net/wiki/spaces/PR/pages/288424408/Creating+a+GitHub+Pull+Request)

### CODE REVIEW

**Comment by hrishileanplum** [comment]
It uses our LogAPI which is brand new network api. And its not total copy paste. This is useful in various locations, especially swizzling logic, where Leanplum Logging is used especially handing error cases. Also, we should have this in place as it also sends logging data to our backend.

**Comment by milos1290** [comment]
We need to decide on how various options should be enabled/disabled, ideally appIds,keys,swizzling, maybe logging, should be set by using the plist file and avoid setting it up in runtime. This will remove the need of having order of initalization, i.e some method must be called before start method etc.

**Comment by hrishileanplum** [comment]
We already have option to enable / disable logs on the client side. I guess what Mayank mentioned was logging feature is completely disabled and not used at all. Especially due to cost reasons.

**Comment by e7mac** [comment]
closing this for now, but keeping the PR around

**Pull request closed without merging**
